FROM node:26-alpine AS builder

RUN npm install -g pnpm@10.33.2

WORKDIR /home/eventmanagement/frontend

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --frozen-lockfile

COPY . .

RUN pnpm build

#Now, for the final build
FROM nginx:1.31-alpine

COPY --from=builder /home/eventmanagement/frontend/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]
